package com.jonathan.project;

//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Fri Jan 14 00:45:50 PST 2000
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
    /* terminals */
    static final int T_ASSIGN = 45;
    static final int T_BOOLEAN = 36;
    static final int T_STR_LITERAL = 69;
    static final int T_PLUS = 61;
    static final int T_BAR = 46;
    static final int T_EXIT = 12;
    static final int T_RBRACKET = 63;
    static final int T_INT_LITERAL = 72;
    static final int T_ARROW = 44;
    static final int T_IS = 17;
    static final int T_LBRACE = 54;
    static final int T_TYPE = 31;
    static final int T_STAR = 68;
    static final int T_IN = 16;
    static final int T_LT = 57;
    static final int T_LPAREN = 56;
    static final int T_LOOP = 18;
    static final int T_THEN = 29;
    static final int T_BY = 4;
    static final int T_REAL_LITERAL = 73;
    static final int T_LTE = 58;
    static final int T_TRUE = 42;
    static final int T_IF = 14;
    static final int T_WITH = 35;
    static final int T_RETURN = 28;
    static final int T_MOD = 19;
    static final int T_ID = 74;
    static final int T_ELSIF = 10;
    static final int T_PROCEDURE = 25;
    static final int T_OR = 23;
    static final int T_SEMI = 65;
    static final int T_CONST = 6;
    static final int T_DOTDOT = 49;
    static final int T_CHAR_LITERAL = 70;
    static final int T_ELSE = 9;
    static final int T_EOF = 71;
    static final int T_INTEGER = 39;
    static final int T_ARRAY = 2;
    static final int T_OF = 22;
    static final int T_IMPORT = 15;
    static final int T_BEGIN = 3;
    static final int T_UNTIL = 32;
    static final int T_WHILE = 34;
    static final int EOF = 0;
    static final int T_RBRACE = 62;
    static final int T_REPEAT = 27;
    static final int T_POINTER = 24;
    static final int T_NIL = 21;
    static final int T_MODULE = 20;
    static final int T_RPAREN = 64;
    static final int T_DIV = 7;
    static final int error = 1;
    static final int T_AMPERSAND = 43;
    static final int T_EQU = 51;
    static final int T_FALSE = 38;
    static final int T_COLON = 47;
    static final int T_NEW = 40;
    static final int T_LBRACKET = 55;
    static final int T_SLASH = 67;
    static final int T_NEQ = 60;
    static final int T_END = 11;
    static final int T_DO = 8;
    static final int T_CHAR = 37;
    static final int T_TILDE = 66;
    static final int T_GT = 52;
    static final int T_FOR = 13;
    static final int T_DOT = 50;
    static final int T_MINUS = 59;
    static final int T_RECORD = 26;
    static final int T_VAR = 33;
    static final int T_TO = 30;
    static final int T_GTE = 53;
    static final int T_COMMA = 48;
    static final int T_REAL = 41;
    static final int T_CASE = 5;
}

